### PR TITLE
New accounts update database to add user profiles

### PR DESCRIPTION
**Pull request by marc-lopez**
For review @csyu1 @noelsison2 

Reservation field not yet present for Customer profiles.

Permissions are currently handled by using adding permission groups 'Customer' and 'Staff'. Is this sufficient for #16?

### CODE REVIEW

**Comment by noelsison** [comment]
I think using Django's permission group added confusion in determining user type. We should talk discuss this task one more time before implementing the changes:

**RRS/accounts/models.py**
- Model names are confusing. I expected UserProfile to be the super class of both CustomerProfile and StaffProfile. Consider changing "UserProfile" into MyUser (or any name shows it is a User model) and change "UserTypeProfile" to "UserProfile"
- Instead of putting is_usertype checks directly to the User model, I think it is easier to add it into UserTypeProfile. This way, the User does not have to be modified

**RRS/accounts/admin.py**
- 10: Why is user unregistered? Is this to hide the functionality that allows a user to be added into both customer and staff groups? :P

**RRS/accounts/models.py**
- 4: UserProfile is actualy a modified User model?
- 9,12: Use self.groups.filter(name='NAME').exists() instead of length
- If you do not plan to use the QuerySet objects, using QuerySet methods such as exists() and count() [is more efficient](https://docs.djangoproject.com/en/1.7/ref/models/querysets/#django.db.models.query.QuerySet.count)
- As indicated in the March 27 minutes: User can only have only one profile: either CustomerProfile or StaffProfile. Consider changing is_customer and is_restaurant_staff to check what kind of profile type the user has instead of what permission group it belongs to, since the current implementation allows us to add a user to both customer and staff types programatically

**RRS/accounts/tests.py**
- 6: This looks good. We should use fixtures for all db related tests

**RRS/accounts/tests.py**
- 12: Does this get the 1st object in UserProfile?

**Comment by marc-lopez** [comment]
**RRS/accounts/models.py**
- Model names are confusing. I expected UserProfile to be the super class of both CustomerProfile and StaffProfile. Consider changing "UserProfile" into MyUser (or any name shows it is a User model) and change "UserTypeProfile" to "UserProfile"
  
  _I will change "UserProfile" into "ExtendedUser" at the moment, since this model is intended to be an expansion from the built-in Django User_
- Instead of putting is_usertype checks directly to the User model, I think it is easier to add it into UserTypeProfile. This way, the User does not have to be modified
  
  _I will try to add a user type abstract getter method in UserTypeProfile that will return a string representation of the actual user type._

**RRS/accounts/admin.py**
- 10: Why is user unregistered? Is this to hide the functionality that allows a user to be added into both customer and staff groups? :P
  
  _User is unregistered because the current version uses the UserProfile extension of User to represent those registered at the site_

**RRS/accounts/models.py**
- 4: UserProfile is actualy a modified User model?
  
  _[Yes](https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#extending-user)_
- 9,12: Use self.groups.filter(name='NAME').exists() instead of length
  
  _Will do_
- As indicated in the March 27 minutes: User can only have only one profile: either CustomerProfile or StaffProfile. Consider changing is_customer and is_restaurant_staff to check what kind of profile type the user has instead of what permission group it belongs to, since the current implementation allows us to add a user to both customer and staff types programatically
  
  _The implementation can block attempts to assign both user types to a single user. I'm leaving a provision in which it is possible for such a scenario to occur based on our decision in this question: "Should a staff in restaurant A be able to place reservations in restaurant B?"_

**RRS/accounts/tests.py**
- 12: Does this get the 1st object in UserProfile?
  
  _No, a new UserProfile is created with a dummy user ID_

---

**Additional questions**
1. Should a staff in restaurant A be able to place reservations in restaurant B? That would mean that this particular user is _both_ a customer and a staff.
2. Regarding the User model, would this work?
_Reservations and an associated restaurant are nullable fields for all Users for archival purposes: all reservations ever made by a user are stored, even if we say that for some reason, this user is no longer of Customer type. Permission groups can be used to distinguish between users that are currently customers or staff members._

**Comment by noelsison** [comment]
Ignore previous code review. Check c5c3d75d33d1ebede16f405deec80b035c6cf200 for suggested minor refactor.

I agree that reservations and an associated restaurant should be nullable so that these stored even if the user has been deleted.

As for distinguishing user types, I think checking their profile type is more reliable.

**Comment by noelsison** [comment]
This looks better and is more flexible

**Comment by noelsison** [comment]
**RRS/accounts/tests.py**
- 32, 36: Are these functions still needed?

**Comment by marc-lopez** [comment]
Not anymore. Will delete

**Pull request merged**
