### PR TITLE
Social sign in through django-allauth

### PR DESCRIPTION
**Pull request by noelsison**
Working OAuth sign in with:
- Google
- Facebook (must have a verified account to be added to app developers)
- Twitter

For review and testing @csyu1 @marc-lopez

### CODE REVIEW

**Comment by marc-lopez** [comment]
Are there any new module requirements?

---

Twitter works fine. The others, not yet.

image

image

**Comment by marc-lopez** [comment]
Twitter works fine. The others, not yet.

image

image

**Comment by noelsison** [comment]
@marc-lopez do you have a verified Facebook account? It is needed so I can give you access while the app is still in test mode.

I'll recheck Google and add update requirements.txt

**Comment by noelsison** [comment]
Google redirect_uri is set to `http://127.0.0.1:8000/accounts/google/login/callback/`. Try using 127.0.0.1 for domain instead of localhost

**Comment by marc-lopez** [comment]
I used 127.0.0.1 for google and now it works. Facebook still doesn't work even after I verified my account. I will try again later

**Comment by noelsison** [comment]
Try confirming your developer access in Facebook

**Comment by noelsison** [comment]
Handle multiple social logins with the same email first before merging

**Pull request closed without merging**
